### ISSUE TITLE
qo-dl_reborn InvalidAppSecret trouble help

### ISSUE THREAD

**Issue by qiuxia54666** [Sorrow446/HRA-Downloader#1]
Thank you for your HRA-Downloader and qo-dl_reborn,they are very very useful, I've been using it till today. But the qo-dl_reborn has the InvalidAppSecret trouble now,would you please fix it? Thank you very much!

**Comment by Sorrow446** [comment]
I archived reborn 2 years ago, no longer working on it. Sorry.
